### ISSUE TITLE
SocketServer Error - "Interrupted system call"

### ISSUE THREAD

**Issue by mojolab** [cnobile2012/django-pam#1]
On trying to authenticate with a system user, I get the following error - 

[07/Jun/2016 17:33:49] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1724
Unhandled exception in thread started by <function wrapper at 0x1f10410>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 144, in inner_run
    ipv6=self.use_ipv6, threading=threading)
  File "/usr/local/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 193, in run
    httpd.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 225, in serve_forever
    r, w, e = select.select([self], [], [], poll_interval)
select.error: (4, 'Interrupted system call')

If I stop the server and start it again, and revisit the admin url, it automatically logs me in. 

Please let me know what further information you need to advise.

**Comment by cnobile2012** [comment]
A few questions.
1. Is the system user a UNIX user or a Django superuser?
2. If you comment out my PAM backend in your settings does the problem still happen?

The errors seem to be happening in the socket server during a request. This would indicate the issue is not in any of the backend auth plugins. Also, there is nothing in your traceback that mentions any of my code.

**Comment by mojolab** [comment]
Thanks for responding! Answers inline

On Tue, Jun 7, 2016 at 11:59 PM, Carl J. Nobile notifications@github.com
wrote:

> A few questions.
> 1. Is the system user a UNIX user or a Django superuser?
> 
> The user in question for which the login was failing was a linux system
> user. With the same settings a Django superuser logs in fine.
> 1. If you comment out my PAM backend in your settings does the problem
>    still happen?
> 
> I switched to an older fork from here (
> https://github.com/tehmaze/django-pam) (looks like 1.0) and that works fine
> for both system users as well as Django superusers. Using that one for now.
> Can also try and do a test with the 1.0 release from your repo and revert,
> though that will take me a couple of weeks to get around to as Im just
> starting off travel.
> 
> The errors seem to be happening in the socket server during a request.
> This would indicate the issue is not in any of the backend auth plugins.
> Also, there is nothing in your traceback that mentions any of my code.
> 
> The forum posts around the internet seem to agree with your analysis.
> However, since it works with the older release, I figured it might be
> linked.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/cnobile2012/django-pam/issues/1#issuecomment-224371628,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABMaHEoSZNwKUjrgAQgxy9S5_zIG-Y7Cks5qJbiagaJpZM4IwLSS
> .

## 

_Arjun Venkatraman_
हैकर (hacker)/浪人(ronin)/Open Solutions Architect, prefer animals to people,
jungles to cities and linux to windows
_E-mail:_ arjun@mojolab.org
_Mobile:_   +91 89891 61881 (BHO + Roaming)

_Web:_ http://mojolab.org, http://hackergram.org
_Twitter:_ @themojolab, @arjunven, @hackergram

**Comment by arjunven** [comment]
I think you guys have the wrong Arjun!

**Comment by mojolab** [comment]
Not sure how you got looped in! How do I unloop you?

**Comment by cnobile2012** [comment]
I'm not asking you to use a different version. What you need to do is comment out the entry in the settings file like this:

```
# Django auth backends.
AUTHENTICATION_BACKENDS = [
    #'django_pam.auth.backends.PAMBackend',
    'django.contrib.auth.backends.ModelBackend',
    ]
```

This will effectively remove my backend from your django app. If your problem still exists after you do this it is definitely not the fault of `django-pam`.

You should be installing it through pip anyway unless you just want to see my test site running.

Also, remember the user that is doing the authenticating needs to be in the UNIX `shadow` group or all authentications will fail.

**Comment by cnobile2012** [comment]
@arjunven, if you follow me or stared my project you may get emails depending on your settings. In other words you may need to change the settings on getting emails.
