### ISSUE TITLE
Django 3.0 Compatibility issue

### ISSUE THREAD

**Issue by arpadhajdu** [cnobile2012/django-pam#10]
Hi,

I was running a compatibility check with Django 3.0 and the module is not functioning due the change:
- django.utils.six - Remove usage of this vendored library or switch to six.

Would it possible to change "six" instead of the django.utils.six ?

**Comment by cnobile2012** [comment]
There are many apps that need updating not just mine. Over the next few
months I hope to be getting to these. I personally haven't updated to 3.0
because of these same issues will many other packages also.

**Comment by cnobile2012** [comment]
OK, I have finally updated this code to run on Django 3.x versions. Thanks for you patience.
