### ISSUE TITLE
HttpRequest.is_ajax() is deprecated in Django 3.1

### ISSUE THREAD

**Issue by BrownGenius** [cnobile2012/django-pam#15]
See: https://docs.djangoproject.com/en/3.1/releases/3.1/#id2

`request.is_ajax()`

should be replaced with:

`request.headers.get('x-requested-with') == 'XMLHttpRequest'`

**Comment by cnobile2012** [comment]
I fixed this over a year ago, sorry for not updating the issue.

**Comment by cnobile2012** [comment]
Closing
