### ISSUE TITLE
LoginView and LogoutView complete example

### ISSUE THREAD

**Issue by cristian-ciobanu** [cnobile2012/django-pam#7]
Please update the documentation with a complete example for these Login and Logout views. I tried to follow the "example_site" but no luck.
I'm trying to use the LoginView() and LogoutView() but I cannot make to work the LogoutView.
It logs me out successfully when I click LogOut but if I try to access a direct link afterwards it does go to it without asking for login (somehow it bypasses authentication).
I'm using the @method_decorator(login_required() and if I clear the browser cache and logout it works and forces me the login before accessing the desired page.
Also I have and issue with the Logout redirect. After logout I'm trying to redirect to the login page and it does but the URL still display the logout link.
I'm using python 3.7.2 on Debian.

**Comment by cnobile2012** [comment]
I assume you read the docs at ReadTheDocs, right? As mentioned in the README it's at [Django PAM](https://django-pam.readthedocs.io/en/latest/index.html).

From personal experience authorization is always a pain to get working properly. The `urls.py` file in the `example_site` directory does not use all the arguments that `Django` provides in the `as_view()` class method, however, my docs do mention what these arguments are. There are a lot of things that need to be in-sync to get redirection working as I intimated above. For one your settings will need to set two variables, the HTML needs to be setup correctly, and the urls need to be correct, If just one of these thing are wrong nothing will seem to work correctly.

I hope you get it working. If you have a GitHub account where your code is I may be able to see where the issues are. I'm somewhat busy, but I'll try to take a look.

**Comment by cristian-ciobanu** [comment]
I do not have the code posted on github yet but i'll post some time in the future.
I managed to make to LogoutView to work properly by creating a custom view for it, I'll close this issue.
Thanks for your support.

**Comment by cnobile2012** [comment]
Great, I'm glad you got it working.
