### ISSUE TITLE
Example to Add User, Log in

### ISSUE THREAD

**Issue by vsoch** [cnobile2012/django-pam#8]
Hey @cnobile2012 ! I just added this module to Singularity Registry Server, and I'm having trouble testing it out. Would it be possible to get an example of how to create a user (in a Docker container) and then log in? I haven't used pam so I'm only familiar with `useradd`. Thank you!

**Comment by vsoch** [comment]
I did

```bash
$ useradd <user> -p <password>
```
first in the container, but no matter what I do, it spins for a second, and then I'm denied:

![image](https://user-images.githubusercontent.com/814322/55172738-e738be80-5150-11e9-8658-f01364e00580.png)

I'll push the branch I'm working on and link here so you can see.

**Comment by vsoch** [comment]
Here is the work in progress -> https://github.com/singularityhub/sregistry/pull/186 thanks for your help!

**Comment by vsoch** [comment]
oh I got it to work! I bound the /etc/shadow and /etc/password from the host (and then used a host user). Do you know why this would work and not creating a user in the container?

**Comment by cnobile2012** [comment]
Creating a user shouldn't be the issue `useradd <user> -p <password>` should be correct. What you need to do is to give that user access to the shadow file as explained in my docs at `Django PAM <http://django-pam.readthedocs.io/en/latest/>`_. It's in the `Configuration` link. It also says what to do in the `README.rst` itself. I don't know much about Docker containers, so I can't help you there. If you are using `mod_wsgi` and you use deamon mode which is highly recomended, then this mode allows you to set a user just for those Apache processes. The user you create should also be the `mod_wsgi` user as this gives you the best security.

**Comment by vsoch** [comment]
Thanks for the quick feedback @cnobile2012 - I did see the instructions in the README, and for Docker (we are root user) I believe root is already in /etc/shadow. I'm not using apache - I'm using nginx with uwsgi, and I start the server like this:

```bash
uwsgi uwsgi.ini
```
and the content of uwsgi.ini:

```bash
[uwsgi]
master = true
processes = 4
threads = 4
socket = :3031
chdir = /code/
post-buffering = true
log-date = true
max-requests = 5000
http-timeout = 3600000
socket-timeout = 120
wsgi-file = shub/wsgi.py
ignore-sigpipe = true
ignore-write-errors = true
disable-write-exception = true
```
And the parameters file:

```bash

uwsgi_param  QUERY_STRING       $query_string;
uwsgi_param  REQUEST_METHOD     $request_method;
uwsgi_param  CONTENT_TYPE       $content_type;
uwsgi_param  CONTENT_LENGTH     $content_length;

uwsgi_param  REQUEST_URI        $request_uri;
uwsgi_param  PATH_INFO          $document_uri;
uwsgi_param  DOCUMENT_ROOT      $document_root;
uwsgi_param  SERVER_PROTOCOL    $server_protocol;
uwsgi_param  HTTPS              $https if_not_empty;

uwsgi_param  REMOTE_ADDR        $remote_addr;
uwsgi_param  REMOTE_PORT        $remote_port;
uwsgi_param  SERVER_PORT        $server_port;
uwsgi_param  SERVER_NAME        $server_name;
```

Do you have experience with the uwsgi module, and we can talk about how the same configuration translates to that?

**Comment by vsoch** [comment]
And here is nginx -

```
  6     1 nginx    S    14260   0%   1   0% nginx: worker process
    1     0 root     S    13812   0%   0   0% nginx: master process nginx -g daemon off;
   25     0 root     S     1528   0%   0   0% sh
   30    25 root     R     1520   0%   1   0% top
```
I tried adding the nginx group and user to the uwsgi container, but that didn't make a difference. I know you aren't super familiar with Docker, but likely if we talk about uwsgi with nginx we can get closer to what the issue was! And if not, it's not a huge deal because the ideal use case is getting users from the host, which seems to work.

**Comment by cnobile2012** [comment]
It's been maybe 3 or 4 years since I've used `uwsgi`. However, the only thing I can say is to never use root to run your processes. If somebody hacks your system they get full root access and I'm sure you don't want that. If memory serves me there are `uid` and a `gid` variables that can be set for each subgroup of processes. Just found this on StackOverflow: https://stackoverflow.com/questions/52890297/uwsgi-doesnt-switch-to-defined-user-uid-my-user-in-custom-uwsgi-ini-file

**Comment by vsoch** [comment]
Okay, so I added a new user and group, uwsgi:

```bash
addgroup --system uwsgi
adduser --disabled-login --system --no-create-home --ingroup uwsgi uwsgi
```
And then specified uwsgi to be the controller in uwsgi.ini

```
[uwsgi]
master = true
processes = 4
threads = 4
socket = :3031
chdir = /code/
uid=uwsgi
gid=uwsgi
post-buffering = true
log-date = true
max-requests = 5000
http-timeout = 3600000
socket-timeout = 120
wsgi-file = shub/wsgi.py
ignore-sigpipe = true
ignore-write-errors = true
disable-write-exception = true
```

The server starts like:

```bash
uwsgi uwsgi.ini
```

I can then look at the logs to confirm that we started (not as root)

```bash
uwsgi_1   | [uWSGI] getting INI configuration from uwsgi.ini
uwsgi_1   | Thu Mar 28 19:49:06 2019 - *** Starting uWSGI 2.0.18 (64bit) on [Thu Mar 28 19:49:06 2019] ***
uwsgi_1   | Thu Mar 28 19:49:06 2019 - compiled with version: 6.3.0 20170516 on 28 March 2019 15:06:34
uwsgi_1   | Thu Mar 28 19:49:06 2019 - os: Linux-4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019
uwsgi_1   | Thu Mar 28 19:49:06 2019 - nodename: 21f5da5145e8
uwsgi_1   | Thu Mar 28 19:49:06 2019 - machine: x86_64
uwsgi_1   | Thu Mar 28 19:49:06 2019 - clock source: unix
uwsgi_1   | Thu Mar 28 19:49:06 2019 - pcre jit disabled
uwsgi_1   | Thu Mar 28 19:49:06 2019 - detected number of CPU cores: 4
uwsgi_1   | Thu Mar 28 19:49:06 2019 - current working directory: /code
uwsgi_1   | Thu Mar 28 19:49:06 2019 - detected binary path: /usr/local/bin/uwsgi
uwsgi_1   | Thu Mar 28 19:49:06 2019 - setgid() to 104
uwsgi_1   | Thu Mar 28 19:49:06 2019 - setuid() to 102
uwsgi_1   | Thu Mar 28 19:49:06 2019 - chdir() to /code/
uwsgi_1   | Thu Mar 28 19:49:06 2019 - your memory page size is 4096 bytes
uwsgi_1   | Thu Mar 28 19:49:06 2019 - detected max file descriptor number: 1048576
uwsgi_1   | Thu Mar 28 19:49:06 2019 - lock engine: pthread robust mutexes
uwsgi_1   | Thu Mar 28 19:49:06 2019 - thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi_1   | Thu Mar 28 19:49:06 2019 - uwsgi socket 0 bound to TCP address :3031 fd 3
uwsgi_1   | Thu Mar 28 19:49:06 2019 - Python version: 3.5.7 (default, Mar 27 2019, 09:19:20)  [GCC 6.3.0 20170516]
uwsgi_1   | Thu Mar 28 19:49:06 2019 - Python main interpreter initialized at 0x55cd7d4ef8c0
uwsgi_1   | Thu Mar 28 19:49:06 2019 - python threads support enabled
uwsgi_1   | Thu Mar 28 19:49:06 2019 - your server socket listen backlog is limited to 100 connections
uwsgi_1   | Thu Mar 28 19:49:06 2019 - your mercy for graceful operations on workers is 60 seconds
uwsgi_1   | Thu Mar 28 19:49:06 2019 - mapped 521440 bytes (509 KB) for 16 cores
uwsgi_1   | Thu Mar 28 19:49:06 2019 - *** Operational MODE: preforking+threaded ***
uwsgi_1   | Thu Mar 28 14:49:06 2019 - WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55cd7d4ef8c0 pid: 77 (default app)
uwsgi_1   | Thu Mar 28 14:49:06 2019 - *** uWSGI is running in multiple interpreter mode ***
uwsgi_1   | Thu Mar 28 14:49:06 2019 - spawned uWSGI master process (pid: 77)
uwsgi_1   | Thu Mar 28 14:49:06 2019 - spawned uWSGI worker 1 (pid: 81, cores: 4)
uwsgi_1   | Thu Mar 28 14:49:06 2019 - spawned uWSGI worker 2 (pid: 85, cores: 4)
uwsgi_1   | Thu Mar 28 14:49:06 2019 - spawned uWSGI worker 3 (pid: 89, cores: 4)
uwsgi_1   | Thu Mar 28 14:49:06 2019 - spawned uWSGI worker 4 (pid: 93, cores: 4)
```
(sorry that's quite a bit of text there!) The id and group correspond to uwsgi:

```bash
root@146f64850faf:/code# id uwsgi
uid=102(uwsgi) gid=104(uwsgi) groups=104(uwsgi),42(shadow)
```

I then logged into the container and added uwsgi to the shadow file:

```bash
root@146f64850faf:/code# cat /etc/shadow

Debian-exim:!:17983:0:99999:7:::
uwsgi:!:17983:0:99999:7:::
```

I'm still getting the same error with logging in. Could this be related to the celery workers? Note that when I look at processes, I don't see any running via uwsgi.

```bash
   1 root      20   0  230980  69140  12084 S   0.0  0.3   0:11.53 celery                                                           
   13 root      20   0  230336  59608   3196 S   0.0  0.3   0:00.00 celery                                                           
   14 root      20   0  230336  59608   3196 S   0.0  0.3   0:00.00 celery                                                           
   15 root      20   0  230336  59608   3196 S   0.0  0.3   0:00.00 celery                                                           
   16 root      20   0  230336  59608   3196 S   0.0  0.3   0:00.00 celery                                                           
   17 root      20   0  238992  61700   4664 S   0.0  0.3   0:00.39 celery
```
hrm, but then I remembered this line:

```
celery worker -A shub.celery -Q default -n default@%h -B
```

and changed it to this:

```
 command: celery worker -A shub.celery --uid uwsgi --gid uwsgi -Q default -n default@%h -B
```

and then the user uwsgi was also running the celery workers:

```bash                                                
    1 uwsgi     20   0  230712  69560  12712 S   0.0  0.3   0:01.82 celery                                                           
   13 uwsgi     20   0       0      0      0 Z   0.0  0.0   0:00.37 celery                                                           
   14 uwsgi     20   0  230324  59764   3420 S   0.0  0.3   0:00.00 celery                                                           
   15 uwsgi     20   0  230324  59764   3420 S   0.0  0.3   0:00.00 celery                                                           
   16 uwsgi     20   0  230324  59764   3420 S   0.0  0.3   0:00.00 celery                                                           
   17 uwsgi     20   0  230324  59768   3420 S   0.0  0.3   0:00.00 celery                                                           
   18 root      20   0   19976   3472   3020 S   0.0  0.0   0:00.02 bash 
```
And added uwsgi again to the shadows file. That didn't seem to work either, unfortunately, but at least now we aren't running as root. Any other ideas?

**Comment by cnobile2012** [comment]
Did you ever run `$ sudo usermod -a -G shadow uwsgi`? If not then the uwsgi user does not have access to the shadow file. You could always chek the `/etc/group` file, there should be a line like this `shadow:x:42:uwsgi`. The number 42 could be different on your system.

**Comment by vsoch** [comment]
Yes, definitely, I ran the command and (shown above) uwsgi is in /etc/shadow. I didn't check the /etc/group file, so I'll do that now:

```bash
root@701cd7041b5c:/code# cat /etc/group | grep shadow
shadow:x:42:uwsgi
```
Looks like I got 42 as well! :)

**Comment by cnobile2012** [comment]
I'm not sure I know how to help at this point. The only thing I can say is concerning Docker. As I said I'm not very familiar with Docker, but if the environment in a Docker instance is identical to a standard Linux instance then obviously it needs to set up exactly like a Linux instance. Anyway, this may give you a lead as to where it's breaking down. I assume you're getting a user not authorized error somewhere.

**Comment by vsoch** [comment]
okay, thanks. If you can't help anymore I can close the issue. Thanks again for your help/
